### ISSUE TITLE
Tab query

### ISSUE THREAD

**Issue by shmshd** [mustafaozcan/MaterialNavigation#1]
Hi Mustafa,

As im new to Android Development im having some questions and i dont understand some of your codes.
Q1. How can rename all the tabs (more than 2) to my own custom names from auto generated names? 
Q2. How can i edit the tabs layout and all? could you please show me one example?

Please provide the answer as im waiting for your quick response :)

**Comment by mustafaozcan** [comment]
Hi,
A1. You can change tab name with getPageTitle function in ContentFragmentAdapter. You can decide tab name with simple switch statement by position.
A2. You can change content of tab in onCreateView in ContentFragment. You can check pageIndex variable and change content.

**Comment by shmshd** [comment]
Can you give an example for A1 ?

**Comment by mustafaozcan** [comment]
public CharSequence getPageTitle(int position) {
        switch (position){
            case 0:
                return "Smart Phone";
            case 1:
                return "Tablet";
            case 2:
                return "PC";
            default:
                return "Unknown";
        }
}

**Comment by shmshd** [comment]
when I use this codes all other NavigationDrawer fragments also get the same names. Eg. When I click Tab content 2 the same tab names, Tab Content 3 also got the same names. Can you please tell me how to give different names for different Fragments? (eg needed) Thanks

**Comment by mustafaozcan** [comment]
You must pass selected navigation drawer item index to ContentFragmentAdapter class. You already have selected nav.draw. item index with mCurrentSelectedPosition variable in MainActivity. You can change ContentFragmentAdapter constructor method and add new parameter for selected nav.draw. item index. Then you must check in CharSequence method.

This project shows only Material Design navigation sample not a completely app. In the real app you have to array of tabs or contents. So you can integrate this code with yours.

**Comment by shmshd** [comment]
Thanks for the info :)
Please fix your email set up in your web! Yesterday I tried to email you and got error sending email.
Thanks again :)
